name: Docker Image build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: sonarscan-dotnet

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: ["2.1", "3.1", "5.0"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Run tests
        id: build-image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            DOTNET_VERSION=${{ matrix.dotnet }}
          push: ${{ github.event_name == 'push' }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest-${{ matrix.dotnet }}
